baseUrl = "khanshoaib3.github.io/minecraft-access"
languageCode = "en"
title = "Minecraft Access Docs"
enableGitInfo = true
disableKinds = ["taxonomy", "term", "rss"]

[markup.tableOfContents]
ordered = true
